"""empty message

Revision ID: 0001
Revises: 
Create Date: 2021-07-08 10:13:45.157087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_price_name'), 't_price', ['name'], unique=True)
    op.create_table('t_teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_teacher_name'), 't_teacher', ['name'], unique=True)
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_name'), 't_user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_name'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_teacher_name'), table_name='t_teacher')
    op.drop_table('t_teacher')
    op.drop_index(op.f('ix_t_price_name'), table_name='t_price')
    op.drop_table('t_price')
    # ### end Alembic commands ###
