"""empty message

Revision ID: 0003
Revises: 0002
Create Date: 2021-07-08 10:43:51.487117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_price', sa.Column('last_modify_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_price', 'last_modify_date')
    # ### end Alembic commands ###
