"""empty message

Revision ID: 0004
Revises: 0003
Create Date: 2021-07-09 07:28:57.574130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('email_address', sa.String(length=32), nullable=True))
    op.add_column('t_user', sa.Column('phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'phone')
    op.drop_column('t_user', 'email_address')
    # ### end Alembic commands ###
